### PR TITLE
Add Rails 5 compatibility

### LINKED ISSUE #27: Support Rails 5
It seems not working on `rails-5.0.0.beta1.1`.

Here is a migration:

```ruby
class CreateFormulas < ActiveRecord::Migration[5.0]
  def change
    create_table :formulas, comment: 'formula of truth' do |t|
      t.string :name, comment: 'name of formula'
      t.string :code, comment: 'ident'
      t.string :equation, comment: 'equation of formula'

      t.timestamps
    end
  end
end
```

And after run `rails db:migration`, here is what I got from `db/schema.rb`:

```ruby

create_table "formulas", id: false, force: :cascade, options: "ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='formula of truth'", comment: "formula of truth" do |t|
  t.integer  "id"
  t.string   "name"
  t.string   "code"
  t.string   "equation"
  t.datetime "created_at", null: false
  t.datetime "updated_at", null: false
end
```

### PR DESCRIPTION
**Pull request by mgrachev**
Fix #27

### CODE REVIEW

**Comment by 42thcoder** [comment]
```ruby

class CreateFormulas < ActiveRecord::Migration[5.0]
  def change
    create_table :formulas, comment: 'formula' do |t|
      t.string :name, comment: '名字'
      t.string :code, comment: '唯一标示'
      t.string :equation, comment: '计算公式'

      t.timestamps
    end
  end
end

```

And then I got an error, : 

```
undefined method `pk_and_sequence_for' for #<ActiveRecord::ConnectionAdapters::Mysql2Adapter:0x007fd78fc33598>/Users/hackerzhang/work/charge/db/migrate/20160125082401_create_formulas.rb:3:in `change'
```

**Comment by mgrachev** [comment]
Fixed.

**Comment by pinnymz** [comment]
@mgrachev thanks for this PR, but I have a more straightforward fix in the rails4_rewrite branch.  However, it seems that comment support was added in beta4 (for PostgreSQL and MySQL that is) so this project may not be needed for much longer.  I'll see if they can pull in something for SQLite support as well.

**Comment by pinnymz** [comment]
Rails 5 support is now in master
